"""empty message

Revision ID: 123c181f2f8b
Revises: 21d996c3febd
Create Date: 2024-08-25 17:18:54.410435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123c181f2f8b'
down_revision = '21d996c3febd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
